// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kgsA11u9-WS0lYzVPPc_jJsGRWRA4pY',
    appId: '1:181471502632:web:787947ff155e9aaf97b01d',
    messagingSenderId: '181471502632', 
    projectId: 'civicconnect-4012b', 
    authDomain: 'civicconnect-4012b.firebaseapp.com', 
    storageBucket: 'civicconnect-4012b.firebasestorage.app', 
    measurementId: 'G-FVR8DQ8EZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKR9KjiNahWtw0agYN1CSD6xlxw8C-2I0',
    appId: '1:181471502632:android:8adba3e4aa51a83497b01d',
    messagingSenderId: '181471502632',
    projectId: 'civicconnect-4012b',
    storageBucket: 'civicconnect-4012b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsS89skfSSS0Wh4XoY9527WzGYYl3XFE',
    appId: '1:181471502632:ios:825ef700f00ac04297b01d',
    messagingSenderId: '181471502632',
    projectId: 'civicconnect-4012b',
    storageBucket: 'civicconnect-4012b.firebasestorage.app',
    iosBundleId: 'com.LakhiteshVarmaJagadabhi.CivicConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMsS89skfSSS0Wh4XoY9527WzGYYl3XFE',
    appId: '1:181471502632:ios:a6c84fa5b8b5d29a97b01d',
    messagingSenderId: '181471502632',
    projectId: 'civicconnect-4012b',
    storageBucket: 'civicconnect-4012b.firebasestorage.app',
    iosBundleId: 'com.example.assets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kgsA11u9-WS0lYzVPPc_jJsGRWRA4pY',
    appId: '1:181471502632:web:9691ddafad1963a997b01d',
    messagingSenderId: '181471502632',
    projectId: 'civicconnect-4012b',
    authDomain: 'civicconnect-4012b.firebaseapp.com',
    storageBucket: 'civicconnect-4012b.firebasestorage.app',
    measurementId: 'G-WE1JWFJ2FW',
  );
}
